package domain;
/* Generated by Together */

public interface Buffer 
{
   public void set( int value ); // place value into Buffer
   public int get(); // return value from Buffer
} // end interface Buffer
